### ISSUE TITLE
Cannot view deployed site on Fly.Io if not logged-in

### ISSUE THREAD

**Issue by DominicSimpson** [fac26/week-4-gnk#28]
If the user is not logged-in to Fly.Io already, the link on ReadMe takes the user to the sign-in page of Fly.Io, rather than the actual individual page for the app.

**Comment by konstantinakatmada** [comment]
thanks for your review, Dominic! This is the link to the latest release, so I am afraid it is fly.io that is redirecting non-logged in users to the log in page :-/
