### ISSUE TITLE
Might be good to add sanitise and validate functions to the add event form

### ISSUE THREAD

**Issue by LauraK0** [fac26/week-4-gnk#34]
![Screenshot 2023-02-08 at 17 12 12](https://user-images.githubusercontent.com/108976875/217602634-4f80f40f-2bc4-4a38-a4c2-bed7ccb76b8c.png)

**Comment by patdel0** [comment]
<img width="662" alt="image" src="https://user-images.githubusercontent.com/53922624/217650854-47a140e1-a16d-4a41-82bb-7dfc300412e3.png">

😳

**Comment by konstantinakatmada** [comment]
thank you for your review and your screenshot, Laura! we have it, just didn't have the time to merge yet :/
