### ISSUE TITLE
.env exposed

### ISSUE THREAD

**Issue by patdel0** [fac26/week-4-gnk#41]
Consider creating new secrets and adding `.env` to `.gitignore`.

There are bots out there that scrape our repositories for our exposed API Keys and secrets. If we had a paid API Key in our `.env` file, we'd see a big bill at the end of the month.

If we have a look at the `Insights > Traffic` tab in the project, we can see if there's an unusual amount of cloned repositories. 

This is an example of traffic in a FAC project which had its API key exposed on the 11/10 and again on 11/14
![image](https://user-images.githubusercontent.com/53922624/202247298-6e3181d6-cf1e-4c6d-adf5-ae325116bc4b.png)

**Comment by konstantinakatmada** [comment]
poignant review. thanks so much, Gal
